BuddySystem/Controllers/BuddyController.cs
using BuddySystem.Data;
using BuddySystem.Models;
using BuddySystem.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuddySystem.Controllers
{
    [Authorize]
    public class BuddyController : Controller
    {
        // GET: Buddy
        public ActionResult Index()
        {
            var service = CreateBuddyService();
            var model = service.GetAllBuddies();

            return View(model);
        }

        // GET: Buddy/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Buddy/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BuddyCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateBuddyService();

            if (service.CreateBuddy(model))
            {
                TempData["SaveResult"] = "Your profile was created.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Profile could not be created");
            return View(model);
        }

        // GET: Buddy/Details/{id}
        public ActionResult Details(int id)
        {
            var service = CreateBuddyService();
            var model = service.GetBuddyById(id);
            return View(model);
        }

        // GET: Buddy/Edit/{id}
        public ActionResult Edit(int id)
        {
            var service = CreateBuddyService();
            var detail = service.GetBuddyById(id);
            var model =
                new BuddyEdit
                {
                    BuddyId = detail.BuddyId,
                    Name = detail.Name,
                    CurrentLocation = detail.CurrentLocation,
                    IsApproved = detail.IsApproved,
                    IsMale = detail.IsMale,
                    Age = detail.Age
                };
            return View(model);
        }

        // POST: Buddy/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BuddyEdit model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.BuddyId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateBuddyService();

            if (service.UpdateBuddy(model))
            {
                TempData["SaveResult"] = "Your profile was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your profile could not be updated.");
            return View();
        }

        // GET: Buddy/Delete/{id}
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var service = CreateBuddyService();
            var model = service.GetBuddyById(id);

            return View(model);
        }

        // POST: Buddy/Delete/{id}
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateBuddyService();
            service.DeleteBuddy(id);

            TempData["SaveResult"] = "This profile was deleted.";
            return RedirectToAction("Index");
        }


        private BuddyService CreateBuddyService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new BuddyService(userId);
            return service;
        }

    }
}

BuddySystem/Controllers/TripController.cs
using BuddySystem.Models;
//using BuddySystem.Models.AdditionalBuddy; intellisense required this using statement, but BuddySystem.Models works for Trip Models... why? maybe I'm overlooking something CW
using BuddySystem.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuddySystem.Controllers
{
        [Authorize]
    public class TripController : Controller
    {
        // GET: Trip
        public ActionResult IndexForUser()
        {
            var tripService = CreateTripService();
            IEnumerable<TripListItem> model = tripService.GetTripsForCurrentUser();
            return View(model);
        }
        public ActionResult IndexAllTrips()
        {
            var tripService = CreateTripService();
            IEnumerable<TripListItem> model = tripService.GetAllTrips();
            return View(model);

        }
        //Get: Create
        public ActionResult Create()
        {
            var buddyServiceNoGuid = CreateBuddyServiceNoGuid();
            var listOfBuddies = buddyServiceNoGuid.GetAllBuddies();
            
            ViewBag.ListOfAllBuddies = listOfBuddies;
            return View();
        }
        //Post: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TripCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateTripService();
            if (service.CreateTrip(model))
            {

                return RedirectToAction("IndexAllTrips");
            }
            else
                ModelState.AddModelError("", "Trip could not be created");
            return View(model);
        }

        //Get : Trip/Edit/{id}
        public ActionResult Edit (int id)
        {
            var service = CreateTripService();
            var detail = service.GetTripById(id);
            var model =
                new TripEdit
                {
                    TripId = detail.TripId,
                    StartTime = detail.StartTime,
                    BuddyId = detail.BuddyId,
                    VolunteerId = detail.VolunteerId,
                    StartLocation = detail.StartLocation,
                    ProjectedEndLocation = detail.ProjectedEndLocation,
                    EndLocation = detail.EndLocation,
                    EndTime = detail.EndTime
                };
            return View(model);
        }

        //Post : Trip/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TripEdit model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.TripId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateTripService();

            if (service.UpdateTrip(model))
            {
                TempData["SaveResult"] = "Your trip was updated.";
                return RedirectToAction("IndexAllTrips");
            }

            ModelState.AddModelError("", "Your trip could not be updated.");
            return View();
        }

        // GET: Trip/Details/{id}
        public ActionResult Details(int id)
        {
            var service = CreateTripService();
            var model = service.GetTripById(id);
            return View(model);
        }

        // GET: Trip/Delete/{id}
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var service = CreateTripService();
            var model = service.GetTripById(id);

            return View(model);
        }

        // POST: Trip/Delete/{id}
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateTripService();
            service.DeleteTrip(id);

            TempData["SaveResult"] = "This profile was deleted.";
            return RedirectToAction("IndexAllTrips");
        }

        //Get: Trip/AddAdditionBuddy/{id}       Gets a model with trip Id & some details from button click -- need to add button to detail/index views
        public ActionResult AddAdditionalBuddy(int id)
        {
            var additionalBuddyService = CreateAdditionalBuddyService();
            var model = additionalBuddyService.GetAddAdditionalBuddyModel(id);
            ViewBag.ListOfAllBuddies = CreateBuddyServiceNoGuid().GetAllBuddies();
            
            return View(model);
        }

        //Post: Trip/Details{id} double check that its directing to proper views... won't matter in API probably
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAdditionalBuddy(AddAdditionalBuddy model)
        {
           // var artistService = NewArtistService();
            if (!ModelState.IsValid)
            {
                ViewBag.AdditionalBuddyID = new SelectList(CreateBuddyServiceNoGuid().GetAllBuddies(), "BuddyId", "Name");
                ViewBag.ListOfAllBuddies = CreateBuddyServiceNoGuid().GetAllBuddies();
                return View(model);
            }

            if (CreateAdditionalBuddyService().PostAdditionalBuddyToDataTable(model))
            {
                //TempData["SaveResult"] = "Buddy was added to Trip.";
                var id = model.TripId;
                return RedirectToAction("Details", new { id = model.TripId });
            }
            else
                ModelState.AddModelError("", "Buddy could not be added");
            return RedirectToAction("IndexAllTrips");
        }



        private TripService CreateTripService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new TripService(userId);
            return service;
        }
        private BuddyService CreateBuddyServiceNoGuid()
        {
            var buddyServiceNoGuid = new BuddyService();
            return buddyServiceNoGuid;
        }
        private AdditionalBuddyService CreateAdditionalBuddyService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var additionalBuddyService = new AdditionalBuddyService(userId);
            return additionalBuddyService;
        }
    }
}

BuddySystem/Views/Buddy/Create.cshtml
@model BuddySystem.Models.BuddyCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BuddyCreate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsApproved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsApproved)
                    @Html.ValidationMessageFor(model => model.IsApproved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMale)
                    @Html.ValidationMessageFor(model => model.IsMale, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BuddySystem/Views/Buddy/Delete.cshtml
@model BuddySystem.Models.BuddyDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BuddyDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BuddyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuddyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsMale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsMale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BuddySystem/Views/Buddy/Details.cshtml
@model BuddySystem.Models.BuddyDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BuddyDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BuddyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuddyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsMale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsMale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BuddyId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BuddySystem/Views/Buddy/Edit.cshtml
@model BuddySystem.Models.BuddyEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BuddyEdit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BuddyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuddyId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuddyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsApproved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsApproved)
                    @Html.ValidationMessageFor(model => model.IsApproved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMale)
                    @Html.ValidationMessageFor(model => model.IsMale, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BuddySystem/Views/Buddy/Index.cshtml
@model IEnumerable<BuddySystem.Models.BuddyListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BuddyId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentLocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsApproved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsMale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BuddyId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentLocation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsApproved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsMale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.ActionLink("Create Trip", "Create", "Trip", new { id = item.BuddyId }, null) |
            @Html.ActionLink("Edit", "Edit", new { id = item.BuddyId }) |
            @Html.ActionLink("Details", "Details", new { id = item.BuddyId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.BuddyId })
        </td>
    </tr>
}

</table>